package Acme::CPANLists::Import::SHARYANTO::IndonesianLanguage;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://blogs.perl.org/users/steven_haryanto/2012/08/cpan-modules-for-the-indonesian-language.html] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"Lingua::ID::Nums2Words"},{module=>"Lingua::ID::Words2Nums"},{module=>"Lingua::Identify"},{module=>"Lingua::Translate::Google"},{module=>"Locale::ID::GuessGender::FromFirstName"},{module=>"Parse::Number::ID"},{module=>"WWW::Google::Translate"}],summary=>"CPAN modules for the Indonesian language (2012)"});

1;
# ABSTRACT: CPAN modules for the Indonesian language (2012)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://blogs.perl.org/users/steven_haryanto/2012/08/cpan-modules-for-the-indonesian-language.html> (retrieved on 2016-02-21). For the full article, visit the URL.

