package Acme::CPANLists::Import::SHARYANTO::INI;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://blogs.perl.org/users/steven_haryanto/2010/11/comparison-of-ini-format-modules-on-cpan.html] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"Config::Format::INI"},{module=>"Config::INI::Access"},{module=>"Config::INI::Writer"},{module=>"Config::IniFiles"},{module=>"Tie::Cfg"}],summary=>"Comparison of INI-format modules on CPAN (2010)"});

1;
# ABSTRACT: Comparison of INI-format modules on CPAN (2010)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://blogs.perl.org/users/steven_haryanto/2010/11/comparison-of-ini-format-modules-on-cpan.html> (retrieved on 2016-02-21). For the full article, visit the URL.


=over

=item * [2016-02-21] Since this article was written, I have also published: L<IOD>, L<Config::IOD>, L<Config::IOD::Reader>.

=back




