package Acme::CPANLists::Import::SHARYANTO::LoggingFrameworks;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://blogs.perl.org/users/steven_haryanto/2010/11/short-grossly-incomplete-comparison-of-perl-logging-frameworks.html] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"Log::Any"},{module=>"Log::Any::App"},{module=>"Log::Dispatch"},{module=>"Log::Dispatchoulli"},{module=>"Log::Fast"},{module=>"Log::Log4perl"},{module=>"String::Flogger"}],summary=>"(Short, grossly incomplete) comparison of Perl logging frameworks (2010)"});

1;
# ABSTRACT: (Short, grossly incomplete) comparison of Perl logging frameworks (2010)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://blogs.perl.org/users/steven_haryanto/2010/11/short-grossly-incomplete-comparison-of-perl-logging-frameworks.html> (retrieved on 2016-02-21). For the full article, visit the URL.


=over

=item * [2016-02-21] Since this article was written, I have also published: L<Log::Any::App>, and plan to release L<Log::Gurat>.

=back




