package Acme::CPANLists::Import::SHARYANTO::Serialization;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://blogs.perl.org/users/steven_haryanto/2010/09/comparison-of-perl-serialization-modules.html] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"Data::Dump"},{module=>"Data::Dump::PHP"},{module=>"Data::Dump::Partial"},{module=>"Data::Dumper"},{module=>"Data::Serializer"},{module=>"YAML::Syck"},{module=>"YAML::Tiny"},{module=>"YAML::XS"}],summary=>"Comparison of Perl serialization modules (2010)"});

1;
# ABSTRACT: Comparison of Perl serialization modules (2010)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://blogs.perl.org/users/steven_haryanto/2010/09/comparison-of-perl-serialization-modules.html> (retrieved on 2016-02-21). For the full article, visit the URL.


=over

=item * [2016-02-21] L<Sereal> is mentioned in the comments.

=item * [2016-02-21] Since this article was written, I have also published: L<Data::Dmp>.

=back




