package Acme::CPANLists::Import::SHARYANTO::SyntaxHighlighting;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://blogs.perl.org/users/steven_haryanto/2012/11/the-sad-state-of-syntax-highlighting-libraries-on-cpan.html] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"Source::SyntaxHighlight"},{module=>"c2html"}],summary=>"The sad state of syntax highlighting libraries on CPAN (2012)"});

1;
# ABSTRACT: The sad state of syntax highlighting libraries on CPAN (2012)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://blogs.perl.org/users/steven_haryanto/2012/11/the-sad-state-of-syntax-highlighting-libraries-on-cpan.html> (retrieved on 2016-02-21). For the full article, visit the URL.

