package Acme::CPANLists::Import::SHARYANTO::TextTables;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://blogs.perl.org/users/steven_haryanto/2014/07/benchmarking-several-ascii-table-generator-modules.html] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"Catmandu::Exporter::Table"},{module=>"Data::ShowTable"},{module=>"Table::Simple"},{module=>"Text::ANSITable"},{module=>"Text::ASCIITable"},{module=>"Text::FormatTable"},{module=>"Text::MarkdownTable"},{module=>"Text::SimpleTable"},{module=>"Text::SimpleTable::AutoWidth"},{module=>"Text::Table"},{module=>"Text::Table::Tiny"},{module=>"Text::TabularDisplay"},{module=>"Text::UnicodeBox::Table"}],summary=>"Benchmarking several ASCII-table-generator modules (2014)"});

1;
# ABSTRACT: Benchmarking several ASCII-table-generator modules (2014)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://blogs.perl.org/users/steven_haryanto/2014/07/benchmarking-several-ascii-table-generator-modules.html> (retrieved on 2016-02-21). For the full article, visit the URL.

